// ─── INDIAN LANGUAGES ─────────────────────────────────────────
export const LANGUAGES = [
  { code: "en",    name: "English",    native: "English",   flag: "🇬🇧" },
  { code: "hi",    name: "Hindi",      native: "हिन्दी",      flag: "🇮🇳" },
  { code: "ta",    name: "Tamil",      native: "தமிழ்",       flag: "🏳️" },
  { code: "te",    name: "Telugu",     native: "తెలుగు",       flag: "🏳️" },
  { code: "ml",    name: "Malayalam",  native: "മലയാളം",     flag: "🏳️" },
  { code: "kn",    name: "Kannada",    native: "ಕನ್ನಡ",        flag: "🏳️" },
  { code: "mr",    name: "Marathi",    native: "मराठी",        flag: "🏳️" },
  { code: "bn",    name: "Bengali",    native: "বাংলা",        flag: "🏳️" },
  { code: "gu",    name: "Gujarati",   native: "ગુજરાતી",     flag: "🏳️" },
  { code: "pa",    name: "Punjabi",    native: "ਪੰਜਾਬੀ",      flag: "🏳️" },
];

export const UI_STRINGS = {
  en: { home: "Home", movies: "Movies", series: "Series", watchlist: "Watchlist", profile: "Profile", login: "Login", signup: "Sign Up", signout: "Sign Out", search: "Search…", trending: "Trending Now", newReleases: "New Releases", recommended: "Recommended For You", continueWatching: "Continue Watching", settings: "Settings", subscription: "Subscription", language: "Language", plan: "Plan", watchNow: "Watch Now", moreInfo: "More Info", addWatchlist: "Add to Watchlist", chooseplan: "Choose Your Plan" },
  hi: { home: "होम", movies: "फ़िल्में", series: "सीरीज़", watchlist: "वॉचलिस्ट", profile: "प्रोफ़ाइल", login: "लॉगिन", signup: "साइन अप", signout: "साइन आउट", search: "खोजें…", trending: "ट्रेंडिंग", newReleases: "नई फ़िल्में", recommended: "आपके लिए अनुशंसित", continueWatching: "देखना जारी रखें", settings: "सेटिंग्स", subscription: "सदस्यता", language: "भाषा", plan: "प्लान", watchNow: "अभी देखें", moreInfo: "अधिक जानकारी", addWatchlist: "वॉचलिस्ट में जोड़ें", chooseplan: "अपना प्लान चुनें" },
  ta: { home: "முகப்பு", movies: "திரைப்படங்கள்", series: "தொடர்கள்", watchlist: "பார்வை பட்டியல்", profile: "சுயவிவரம்", login: "உள்நுழை", signup: "பதிவு செய்", signout: "வெளியேறு", search: "தேடு…", trending: "டிரெண்டிங்", newReleases: "புதிய வெளியீடுகள்", recommended: "உங்களுக்கான பரிந்துரை", continueWatching: "தொடர்ந்து பார்க்கவும்", settings: "அமைப்புகள்", subscription: "சந்தா", language: "மொழி", plan: "திட்டம்", watchNow: "இப்போது பாருங்கள்", moreInfo: "மேலும் தகவல்", addWatchlist: "பார்வை பட்டியலில் சேர்", chooseplan: "உங்கள் திட்டத்தை தேர்வு செய்யுங்கள்" },
  te: { home: "హోమ్", movies: "సినిమాలు", series: "సీరీస్", watchlist: "వాచ్‌లిస్ట్", profile: "ప్రొఫైల్", login: "లాగిన్", signup: "సైన్ అప్", signout: "సైన్ అవుట్", search: "వెతుకు…", trending: "ట్రెండింగ్", newReleases: "కొత్త విడుదలలు", recommended: "మీకు సిఫారసు చేయబడింది", continueWatching: "చూడడం కొనసాగించు", settings: "సెట్టింగ్స్", subscription: "సభ్యత్వం", language: "భాష", plan: "ప్లాన్", watchNow: "ఇప్పుడు చూడండి", moreInfo: "మరింత సమాచారం", addWatchlist: "వాచ్‌లిస్ట్‌కు జోడించు", chooseplan: "మీ ప్లాన్ ఎంచుకోండి" },
  ml: { home: "ഹോം", movies: "ചലച്ചിത്രങ്ങൾ", series: "പരമ്പരകൾ", watchlist: "വാച്ച്‌ലിസ്റ്റ്", profile: "പ്രൊഫൈൽ", login: "ലോഗിൻ", signup: "സൈൻ അപ്പ്", signout: "സൈൻ ഔട്ട്", search: "തിരയുക…", trending: "ട്രെൻഡിങ്", newReleases: "പുതിയ റിലീസുകൾ", recommended: "നിങ്ങൾക്കായി ശുപാർശ ചെയ്തത്", continueWatching: "കാണൽ തുടരുക", settings: "ക്രമീകരണങ്ങൾ", subscription: "സബ്‌സ്‌ക്രിപ്ഷൻ", language: "ഭാഷ", plan: "പ്ലാൻ", watchNow: "ഇപ്പോൾ കാണുക", moreInfo: "കൂടുതൽ വിവരങ്ങൾ", addWatchlist: "വാച്ച്‌ലിസ്റ്റിൽ ചേർക്കുക", chooseplan: "നിങ്ങളുടെ പ്ലാൻ തിരഞ്ഞെടുക്കുക" },
  kn: { home: "ಮುಖಪುಟ", movies: "ಚಲನಚಿತ್ರಗಳು", series: "ಸರಣಿ", watchlist: "ವಾಚ್‌ಲಿಸ್ಟ್", profile: "ಪ್ರೊಫೈಲ್", login: "ಲಾಗಿನ್", signup: "ಸೈನ್ ಅಪ್", signout: "ಸೈನ್ ಔಟ್", search: "ಹುಡುಕು…", trending: "ಟ್ರೆಂಡಿಂಗ್", newReleases: "ಹೊಸ ಬಿಡುಗಡೆಗಳು", recommended: "ನಿಮಗಾಗಿ ಶಿಫಾರಸು", continueWatching: "ವೀಕ್ಷಣೆ ಮುಂದುವರಿಸಿ", settings: "ಸೆಟ್ಟಿಂಗ್‌ಗಳು", subscription: "ಚಂದಾದಾರಿಕೆ", language: "ಭಾಷೆ", plan: "ಯೋಜನೆ", watchNow: "ಈಗ ವೀಕ್ಷಿಸಿ", moreInfo: "ಹೆಚ್ಚಿನ ಮಾಹಿತಿ", addWatchlist: "ವಾಚ್‌ಲಿಸ್ಟ್‌ಗೆ ಸೇರಿಸಿ", chooseplan: "ನಿಮ್ಮ ಯೋಜನೆ ಆಯ್ಕೆಮಾಡಿ" },
  mr: { home: "मुखपृष्ठ", movies: "चित्रपट", series: "मालिका", watchlist: "वॉचलिस्ट", profile: "प्रोफाइल", login: "लॉगिन", signup: "साइन अप", signout: "साइन आउट", search: "शोधा…", trending: "ट्रेंडिंग", newReleases: "नवीन प्रकाशने", recommended: "तुमच्यासाठी शिफारस", continueWatching: "पाहणे सुरू ठेवा", settings: "सेटिंग्ज", subscription: "सदस्यता", language: "भाषा", plan: "प्लान", watchNow: "आता पहा", moreInfo: "अधिक माहिती", addWatchlist: "वॉचलिस्टमध्ये जोडा", chooseplan: "तुमचा प्लान निवडा" },
  bn: { home: "হোম", movies: "চলচ্চিত্র", series: "সিরিজ", watchlist: "ওয়াচলিস্ট", profile: "প্রোফাইল", login: "লগইন", signup: "সাইন আপ", signout: "সাইন আউট", search: "খুঁজুন…", trending: "ট্রেন্ডিং", newReleases: "নতুন মুক্তি", recommended: "আপনার জন্য প্রস্তাবিত", continueWatching: "দেখা চালিয়ে যান", settings: "সেটিংস", subscription: "সাবস্ক্রিপশন", language: "ভাষা", plan: "প্ল্যান", watchNow: "এখন দেখুন", moreInfo: "আরও তথ্য", addWatchlist: "ওয়াচলিস্টে যোগ করুন", chooseplan: "আপনার পরিকল্পনা বেছে নিন" },
  gu: { home: "હોમ", movies: "ફિલ્મો", series: "સીરિઝ", watchlist: "વૉચલિસ્ટ", profile: "પ્રોફાઇલ", login: "લોગિન", signup: "સાઇન અપ", signout: "સાઇન આઉટ", search: "શોધો…", trending: "ટ્રેન્ડિંગ", newReleases: "નવા પ્રકાશનો", recommended: "તમારા માટે ભલામણ", continueWatching: "જોવાનું ચાલુ રાખો", settings: "સેટિંગ્સ", subscription: "સબ્સ્ક્રિપ્શન", language: "ભાષા", plan: "પ્લાન", watchNow: "હવે જુઓ", moreInfo: "વધુ માહિતી", addWatchlist: "વૉચલિસ્ટમાં ઉમેરો", chooseplan: "તમારી યોજના પસંદ કરો" },
  pa: { home: "ਹੋਮ", movies: "ਫਿਲਮਾਂ", series: "ਸੀਰੀਜ਼", watchlist: "ਵਾਚਲਿਸਟ", profile: "ਪ੍ਰੋਫਾਈਲ", login: "ਲੌਗਇਨ", signup: "ਸਾਈਨ ਅੱਪ", signout: "ਸਾਈਨ ਆਉਟ", search: "ਖੋਜੋ…", trending: "ਟ੍ਰੈਂਡਿੰਗ", newReleases: "ਨਵੀਆਂ ਰਿਲੀਜ਼", recommended: "ਤੁਹਾਡੇ ਲਈ ਸਿਫਾਰਸ਼", continueWatching: "ਦੇਖਣਾ ਜਾਰੀ ਰੱਖੋ", settings: "ਸੈਟਿੰਗਾਂ", subscription: "ਸਬਸਕ੍ਰਿਪਸ਼ਨ", language: "ਭਾਸ਼ਾ", plan: "ਪਲਾਨ", watchNow: "ਹੁਣੇ ਦੇਖੋ", moreInfo: "ਹੋਰ ਜਾਣਕਾਰੀ", addWatchlist: "ਵਾਚਲਿਸਟ ਵਿੱਚ ਜੋੜੋ", chooseplan: "ਆਪਣਾ ਪਲਾਨ ਚੁਣੋ" },
};