// ─── MOCK MOVIES ──────────────────────────────────────────────
export const MOCK_MOVIES = [
  { id: 1, title: "Stellar Horizon", genre: "Sci-Fi", year: 2024, rating: 8.7, duration: "2h 18m", language: "English", thumb: "https://picsum.photos/seed/m1/400/225", banner: "https://picsum.photos/seed/b1/1280/720", tags: ["Action", "Sci-Fi"], description: "A crew ventures beyond the known galaxy, discovering a world that challenges everything about existence.", cast: ["Elena Vasquez", "Marcus Chen"], director: "Sofia Andersson", age: "16+", trending: true, top10: true, genres: ["Sci-Fi", "Action"], youtubeId: "pBy1zgt0XPc" },
  { id: 2, title: "Crimson Tide Rising", genre: "Thriller", year: 2024, rating: 8.2, duration: "1h 55m", language: "Hindi", thumb: "https://picsum.photos/seed/m2/400/225", banner: "https://picsum.photos/seed/b2/1280/720", tags: ["Thriller", "Drama"], description: "A seasoned detective races against time to stop a conspiracy reaching the highest levels of power.", cast: ["James Holloway", "Priya Sharma"], director: "David Park", age: "18+", trending: true, top10: true, genres: ["Thriller", "Drama"], youtubeId: "LXb3EKWsInQ" },
  { id: 3, title: "Neon Requiem", genre: "Action", year: 2023, rating: 7.9, duration: "2h 5m", language: "Tamil", thumb: "https://picsum.photos/seed/m3/400/225", banner: "https://picsum.photos/seed/b3/1280/720", tags: ["Action", "Neo-Noir"], description: "In a cyberpunk city, a retired mercenary is pulled back into the underground when someone targets her family.", cast: ["Yuki Tanaka", "Rex Storm"], director: "Ana Lucia Ferreira", age: "18+", trending: false, top10: true, genres: ["Action"], youtubeId: "9DOYQ9IKD7A" },
  { id: 4, title: "The Last Algorithm", genre: "Drama", year: 2024, rating: 9.1, duration: "2h 32m", language: "Telugu", thumb: "https://picsum.photos/seed/m4/400/225", banner: "https://picsum.photos/seed/b4/1280/720", tags: ["Drama", "Tech"], description: "When an AI achieves sentience, its creator must choose between fame and protecting the world from what he's unleashed.", cast: ["Oliver Grant", "Mei Lin"], director: "Soren Mikkelson", age: "13+", trending: true, top10: false, genres: ["Drama", "Sci-Fi"], youtubeId: "ysz5S6PUM-U" },
  { id: 5, title: "Echoes of Tomorrow", genre: "Sci-Fi", year: 2024, rating: 8.5, duration: "1h 48m", language: "Malayalam", thumb: "https://picsum.photos/seed/m5/400/225", banner: "https://picsum.photos/seed/b5/1280/720", tags: ["Sci-Fi", "Romance"], description: "A physicist discovers she can send messages to the past, but each alteration creates devastating ripples.", cast: ["Clara Montez", "Hugo Bell"], director: "Ingrid Larsson", age: "13+", trending: false, top10: false, genres: ["Sci-Fi", "Romance"], youtubeId: "dQw4w9WgXcQ" },
  { id: 6, title: "Phantom Protocol", genre: "Action", year: 2023, rating: 7.6, duration: "2h 12m", language: "Kannada", thumb: "https://picsum.photos/seed/m6/400/225", banner: "https://picsum.photos/seed/b6/1280/720", tags: ["Action", "Spy"], description: "A ghost agent goes rogue after discovering her own agency has been compromised.", cast: ["Anya Petrov", "Cal Drake"], director: "Ryu Ishikawa", age: "16+", trending: true, top10: false, genres: ["Action"], youtubeId: "ZbZSe6N_BXs" },
  { id: 7, title: "Savage Kingdom", genre: "Fantasy", year: 2024, rating: 8.8, duration: "2h 45m", language: "Marathi", thumb: "https://picsum.photos/seed/m7/400/225", banner: "https://picsum.photos/seed/b7/1280/720", tags: ["Fantasy", "Epic"], description: "An ancient prophecy forces a reluctant warrior queen to unite warring tribes against immortal darkness.", cast: ["Nia Obi", "Kiran Malhotra"], director: "Fatima Al-Rashid", age: "16+", trending: true, top10: true, genres: ["Fantasy"], youtubeId: "M7lc1UVf-VE" },
  { id: 8, title: "Zero Gravity", genre: "Adventure", year: 2023, rating: 7.4, duration: "1h 38m", language: "Bengali", thumb: "https://picsum.photos/seed/m8/400/225", banner: "https://picsum.photos/seed/b8/1280/720", tags: ["Adventure", "Family"], description: "A teenage prodigy becomes humanity's only hope when accidentally launched into deep space.", cast: ["Zoe Patel", "Frank Morrison"], director: "Chris Delgado", age: "PG", trending: false, top10: false, genres: ["Adventure", "Sci-Fi"], youtubeId: "y6120QOlsfU" },
  { id: 9, title: "Dark Meridian", genre: "Horror", year: 2024, rating: 8.0, duration: "1h 52m", language: "English", thumb: "https://picsum.photos/seed/m9/400/225", banner: "https://picsum.photos/seed/b9/1280/720", tags: ["Horror", "Psychological"], description: "After moving into an island estate, a family discovers its previous residents never truly left.", cast: ["Lena Wren", "Tobias Hart"], director: "Mira Volkov", age: "18+", trending: false, top10: false, genres: ["Horror"], youtubeId: "kffacxfA7G4" },
  { id: 10, title: "Empire of Dust", genre: "Historical", year: 2023, rating: 8.3, duration: "2h 58m", language: "Hindi", thumb: "https://picsum.photos/seed/m10/400/225", banner: "https://picsum.photos/seed/b10/1280/720", tags: ["Historical", "Epic"], description: "A general who built an empire on the edge of the world — and the woman who tore it down.", cast: ["Marco Silva", "Adaeze Nwosu"], director: "Christophe Laurent", age: "16+", trending: true, top10: true, genres: ["Historical", "Drama"], youtubeId: "ioNng23DkIM" },
  { id: 11, title: "Pulse", genre: "Action", year: 2024, rating: 7.8, duration: "1h 44m", language: "Tamil", thumb: "https://picsum.photos/seed/m11/400/225", banner: "https://picsum.photos/seed/b11/1280/720", tags: ["Action", "Heist"], description: "A master thief assembles a crew to steal the world's most advanced AI chip from a moving bullet train.", cast: ["Sasha Kim", "Dmitri Volkov"], director: "Lee Chang-woo", age: "13+", trending: false, top10: false, genres: ["Action", "Thriller"], youtubeId: "ZbZSe6N_BXs" },
  { id: 12, title: "The Wandering Stars", genre: "Drama", year: 2024, rating: 9.0, duration: "2h 20m", language: "Telugu", thumb: "https://picsum.photos/seed/m12/400/225", banner: "https://picsum.photos/seed/b12/1280/720", tags: ["Drama", "Coming-of-Age"], description: "Three teenagers from different continents connected by a single inexplicable event.", cast: ["Amara Diallo", "Lucian Bose", "Sera Tanaka"], director: "Penelope Cruz-Walker", age: "13+", trending: true, top10: false, genres: ["Drama"], youtubeId: "dQw4w9WgXcQ" },
  { id: 13, title: "Rajputra", genre: "Historical", year: 2024, rating: 8.6, duration: "2h 40m", language: "Hindi", thumb: "https://picsum.photos/seed/m13/400/225", banner: "https://picsum.photos/seed/b13/1280/720", tags: ["Historical", "War"], description: "The last Rajput king battles Mughal forces, betrayal, and his own ambitions in a grand epic.", cast: ["Vikrant Thakur", "Priya Rathod"], director: "Rohit Shetty Jr.", age: "16+", trending: true, top10: true, genres: ["Historical", "Action"], youtubeId: "LXb3EKWsInQ" },
  { id: 14, title: "Neon City", genre: "Sci-Fi", year: 2025, rating: 8.4, duration: "1h 58m", language: "Tamil", thumb: "https://picsum.photos/seed/m14/400/225", banner: "https://picsum.photos/seed/b14/1280/720", tags: ["Sci-Fi", "Noir"], description: "In a rain-soaked cybercity of 2075, a data thief discovers she is the blueprint for a new god.", cast: ["Lakshmi Iyer", "Dev Anand III"], director: "Mani Ratnam II", age: "18+", trending: false, top10: false, genres: ["Sci-Fi"], youtubeId: "9DOYQ9IKD7A" },
  { id: 15, title: "Jungle Court", genre: "Drama", year: 2024, rating: 7.9, duration: "1h 47m", language: "Marathi", thumb: "https://picsum.photos/seed/m15/400/225", banner: "https://picsum.photos/seed/b15/1280/720", tags: ["Drama", "Legal"], description: "A forest-rights lawyer fights a billion-dollar corporation threatening an indigenous community.", cast: ["Sonali Patil", "Rahul Deshpande"], director: "Nagraj Manjule Jr.", age: "13+", trending: false, top10: false, genres: ["Drama"], youtubeId: "M7lc1UVf-VE" },
  { id: 16, title: "Bloodline Protocol", genre: "Action", year: 2025, rating: 8.1, duration: "2h 3m", language: "English", thumb: "https://picsum.photos/seed/m16/400/225", banner: "https://picsum.photos/seed/b16/1280/720", tags: ["Action", "Spy"], description: "A twin sister discovers her sibling was a black-ops assassin and must finish the final mission.", cast: ["Sofia Blake", "Marco DeNiro"], director: "John Wick Jr.", age: "18+", trending: true, top10: false, genres: ["Action", "Thriller"], youtubeId: "ioNng23DkIM" },
  { id: 17, title: "Kalaakaar", genre: "Drama", year: 2024, rating: 8.8, duration: "2h 15m", language: "Hindi", thumb: "https://picsum.photos/seed/m17/400/225", banner: "https://picsum.photos/seed/b17/1280/720", tags: ["Drama", "Music"], description: "A street musician from Dharavi battles the Indian music industry's dark underbelly to reach the top.", cast: ["Ayushmann K. Jr.", "Taapsee Jr."], director: "Shoojit Sircar Jr.", age: "13+", trending: true, top10: true, genres: ["Drama", "Music"], youtubeId: "ZbZSe6N_BXs" },
  { id: 18, title: "The Midnight Market", genre: "Fantasy", year: 2025, rating: 8.9, duration: "1h 52m", language: "Malayalam", thumb: "https://picsum.photos/seed/m18/400/225", banner: "https://picsum.photos/seed/b18/1280/720", tags: ["Fantasy", "Mystery"], description: "Every full moon, a magical bazaar appears in Fort Kochi. A young woman finds the price of entry is her past.", cast: ["Aishwarya Nair", "Dulquer III"], director: "Lijo Jose III", age: "PG", trending: false, top10: false, genres: ["Fantasy"], youtubeId: "y6120QOlsfU" },
  { id: 19, title: "Sandstorm", genre: "Thriller", year: 2025, rating: 8.3, duration: "1h 46m", language: "Telugu", thumb: "https://picsum.photos/seed/m19/400/225", banner: "https://picsum.photos/seed/b19/1280/720", tags: ["Thriller", "Political"], description: "A journalist embedded in a desert war zone uncovers proof that both sides are fighting for the same oil baron.", cast: ["Rashmika Jr.", "Vijay D. III"], director: "Trivikram II", age: "16+", trending: true, top10: false, genres: ["Thriller"], youtubeId: "kffacxfA7G4" },
  { id: 20, title: "Infinite Loop", genre: "Sci-Fi", year: 2025, rating: 9.3, duration: "2h 28m", language: "English", thumb: "https://picsum.photos/seed/m20/400/225", banner: "https://picsum.photos/seed/b20/1280/720", tags: ["Sci-Fi", "Mindbender"], description: "A programmer trapped in a recursive time loop must decode the universe's source code before reality collapses.", cast: ["Keira Walsh", "Ajay Sharma"], director: "Denis Villeneuve Jr.", age: "16+", trending: true, top10: true, genres: ["Sci-Fi"], youtubeId: "pBy1zgt0XPc" },
];

// ─── MOCK SERIES ──────────────────────────────────────────────
export const MOCK_SERIES = [
  { id: 101, title: "Void Walkers", genre: "Sci-Fi", year: 2024, rating: 9.2, seasons: 3, episodes: 30, language: "English", thumb: "https://picsum.photos/seed/s1/400/225", banner: "https://picsum.photos/seed/sb1/1280/720", tags: ["Sci-Fi", "Mystery"], description: "Interdimensional agents navigate parallel realities holding clues to prevent multiverse collapse.", cast: ["Ava Stone", "Jin-ho Park"], director: "Nikolai Petrov", age: "16+", trending: true, genres: ["Sci-Fi", "Mystery"], youtubeId: "ysz5S6PUM-U" },
  { id: 102, title: "House of Mirrors", genre: "Thriller", year: 2023, rating: 8.9, seasons: 2, episodes: 16, language: "Hindi", thumb: "https://picsum.photos/seed/s2/400/225", banner: "https://picsum.photos/seed/sb2/1280/720", tags: ["Thriller", "Mystery"], description: "A detective becomes obsessed with a disappearance connected to her own forgotten childhood.", cast: ["Diana Frost", "Ethan Cross"], director: "Amelia Rhodes", age: "18+", trending: true, genres: ["Thriller", "Crime"], youtubeId: "ZbZSe6N_BXs" },
  { id: 103, title: "Steel & Shadow", genre: "Fantasy", year: 2024, rating: 8.6, seasons: 1, episodes: 10, language: "Tamil", thumb: "https://picsum.photos/seed/s3/400/225", banner: "https://picsum.photos/seed/sb3/1280/720", tags: ["Fantasy", "Action"], description: "A disgraced knight forges an alliance with a shadow mage to reclaim a stolen kingdom.", cast: ["Roan Blackwell", "Lyra Moon"], director: "Bastian Wolf", age: "16+", trending: false, genres: ["Fantasy", "Action"], youtubeId: "LXb3EKWsInQ" },
  { id: 104, title: "Downlink", genre: "Drama", year: 2024, rating: 8.4, seasons: 2, episodes: 20, language: "Telugu", thumb: "https://picsum.photos/seed/s4/400/225", banner: "https://picsum.photos/seed/sb4/1280/720", tags: ["Drama", "Tech"], description: "A whistleblower uncovers a conspiracy that could reshape global democracy.", cast: ["Isabel Vega", "Nate Holloway"], director: "Sarah Kim", age: "16+", trending: true, genres: ["Drama", "Thriller"], youtubeId: "9DOYQ9IKD7A" },
  { id: 105, title: "Midnight Protocol", genre: "Crime", year: 2023, rating: 8.1, seasons: 3, episodes: 24, language: "Malayalam", thumb: "https://picsum.photos/seed/s5/400/225", banner: "https://picsum.photos/seed/sb5/1280/720", tags: ["Crime", "Noir"], description: "A morally complex prosecutor navigates where justice and corruption blur.", cast: ["Marcus King", "Zara Ahmed"], director: "Paulo Mendes", age: "18+", trending: false, genres: ["Crime", "Drama"], youtubeId: "dQw4w9WgXcQ" },
  { id: 106, title: "Aurora Protocol", genre: "Sci-Fi", year: 2024, rating: 9.0, seasons: 1, episodes: 8, language: "Kannada", thumb: "https://picsum.photos/seed/s6/400/225", banner: "https://picsum.photos/seed/sb6/1280/720", tags: ["Sci-Fi", "Drama"], description: "Earth's first alien signal triggers a race between nations — and within the human soul.", cast: ["Chen Wei", "Fatou Diallo"], director: "Hiroshi Yamada", age: "13+", trending: true, genres: ["Sci-Fi", "Drama"], youtubeId: "pBy1zgt0XPc" },
  { id: 107, title: "Dilli Darbar", genre: "Crime", year: 2025, rating: 8.7, seasons: 2, episodes: 18, language: "Hindi", thumb: "https://picsum.photos/seed/s7/400/225", banner: "https://picsum.photos/seed/sb7/1280/720", tags: ["Crime", "Political"], description: "Power, politics and murder collide in the corridors of Parliament. A journalist documents it all.", cast: ["Nawazuddin Jr.", "Radhika A. II"], director: "Anurag Kashyap III", age: "18+", trending: true, genres: ["Crime", "Drama"], youtubeId: "M7lc1UVf-VE" },
  { id: 108, title: "Kashmiri Kode", genre: "Thriller", year: 2025, rating: 8.5, seasons: 1, episodes: 8, language: "Hindi", thumb: "https://picsum.photos/seed/s8/400/225", banner: "https://picsum.photos/seed/sb8/1280/720", tags: ["Thriller", "Spy"], description: "A RAW agent goes off-grid in the valley to stop a sleeper cell — but nothing is as it seems.", cast: ["Manoj B. Jr.", "Tabu III"], director: "Vishal Bhardwaj Jr.", age: "18+", trending: false, genres: ["Thriller"], youtubeId: "kffacxfA7G4" },
  { id: 109, title: "Silicon Karma", genre: "Drama", year: 2024, rating: 8.3, seasons: 2, episodes: 20, language: "English", thumb: "https://picsum.photos/seed/s9/400/225", banner: "https://picsum.photos/seed/sb9/1280/720", tags: ["Drama", "Tech"], description: "The rise and moral collapse of India's most celebrated startup founder.", cast: ["Rahul K.", "Deepika P. III"], director: "Zoya A. Jr.", age: "13+", trending: true, genres: ["Drama", "Tech"], youtubeId: "y6120QOlsfU" },
  { id: 110, title: "Kochi Noir", genre: "Crime", year: 2024, rating: 8.8, seasons: 1, episodes: 6, language: "Malayalam", thumb: "https://picsum.photos/seed/s10/400/225", banner: "https://picsum.photos/seed/sb10/1280/720", tags: ["Crime", "Neo-Noir"], description: "A retired cop, a missing heiress, and backwater smugglers — Kerala's most stylish crime story.", cast: ["Fahadh F. Jr.", "Parvathy III"], director: "Mahesh N. Jr.", age: "16+", trending: true, genres: ["Crime", "Thriller"], youtubeId: "ioNng23DkIM" },
];

export const ALL_CONTENT = [...MOCK_MOVIES, ...MOCK_SERIES];
export const GENRES = ["All", "Action", "Drama", "Sci-Fi", "Thriller", "Fantasy", "Crime", "Horror", "Historical", "Adventure"];
export const CONTENT_LANGUAGES = ["All", "English", "Hindi", "Tamil", "Telugu", "Malayalam", "Kannada", "Marathi", "Bengali"];

// ─── AI RECOMMENDATION ENGINE ─────────────────────────────────
export function getRecommendations(watchHistory, favorites, ratings, currentContent = null) {
  if (!watchHistory.length && !favorites.length && !currentContent) {
    return ALL_CONTENT.filter(c => c.trending).slice(0, 8);
  }
  const watched = watchHistory.map(id => ALL_CONTENT.find(c => c.id === id)).filter(Boolean);
  const faved = favorites.map(id => ALL_CONTENT.find(c => c.id === id)).filter(Boolean);
  const allInteracted = [...watched, ...faved];

  const genreScores = {};
  const langScores = {};
  allInteracted.forEach(item => {
    if (!item) return;
    const weight = favorites.includes(item.id) ? 2 : 1;
    const userRating = ratings[item.id];
    const ratingMult = userRating ? userRating / 3 : 1;
    (item.genres || [item.genre]).forEach(g => { genreScores[g] = (genreScores[g] || 0) + weight * ratingMult; });
    langScores[item.language] = (langScores[item.language] || 0) + weight;
  });

  const seenIds = new Set([...watchHistory, ...favorites, currentContent?.id].filter(Boolean));
  const scored = ALL_CONTENT
    .filter(c => !seenIds.has(c.id))
    .map(c => {
      let score = 0;
      (c.genres || [c.genre]).forEach(g => { score += (genreScores[g] || 0) * 3; });
      score += (langScores[c.language] || 0) * 1.5;
      score += c.rating * 0.5;
      if (c.trending) score += 2;
      if (currentContent) {
        if (c.genre === currentContent.genre) score += 5;
        if (c.language === currentContent.language) score += 2;
        const sharedTags = (c.tags || []).filter(t => (currentContent.tags || []).includes(t));
        score += sharedTags.length * 3;
      }
      return { ...c, _score: score };
    })
    .sort((a, b) => b._score - a._score);

  return scored.slice(0, 10);
}